### ISSUE TITLE
Page 24: Create an ember partial

### ISSUE THREAD

**Issue by stavarotti** [abuiles/ember-cli-101-errata#105]
The last paragraph on the page states the following:

``` html
Since we will be using the same form for adding a new friend and editing, let’s create an Ember
partial called app/templates/friends/-form.hbs with the following content:
```

but does not state how to create the partial using the CLI generator command.  Is this omission intentional?  How should the user create the partial?

**Comment by abuiles** [comment]
@stavarotti thanks! It's a template file so we can create it manually or using the template generator. I just change it so it includes the generator command:

> Since we will be using the same form for adding a new friend and
> editing, let's create an
> [Ember partial](http://emberjs.com/api/classes/Ember.Handlebars.helpers.html#method_partial)
> we can generate the template for the partial with template generator,
> `ember g template friends/-form` and add the following content:
