### ISSUE TITLE
Page 55: Inconsistent order of props

### ISSUE THREAD

**Issue by stavarotti** [abuiles/ember-cli-101-errata#108]
Minor issue but the order of the properties is different than that used to generate the resources.  E.g., the following command is used to generate the articles resource:

``` bash
ember generate resource articles description:string createdAt:date state:strin\
g notes:string
```

Yet the property order is alpha:

``` javascript
import DS from 'ember-data';
export default DS.Model.extend({
  createdAt: DS.attr('date'),
  description: DS.attr('string'),
  friend: DS.belongsTo('friend'),
  notes: DS.attr('string'),
  state: DS.attr('string')
});
```

Minor pick but it makes things a little disjointed.

**Comment by abuiles** [comment]
Thanks! I've fixed this, it will be available in the next release.
