### ISSUE TITLE
errorMessage stays around forever once it's been set in the controller

### ISSUE THREAD

**Issue by vais** [abuiles/ember-cli-101-errata#111]
Once you set `errorMessage` property on the controller, the error message is displayed in the template next time you return to create a new friend. I vaguely recall that this is a pain point in Ember, so it would be nice to see "the right way" of dealing with this. As the code in the book stands now, it has a bug. Please teach us best practices for managing controller state (or how to avoid the issue altogether).

**Comment by abuiles** [comment]
@vais  thanks for reporting this, actually is not a bug but something intentional. I want people to see this kind of issues, and then if you keep going, you will find how to handle them :)

**Comment by vais** [comment]
I see... I thought that may be it, but I tried to skip ahead to see if you are offering a solution to this further into the book, but couldn't find anything searching for "errorMessage". I guess I'll keep working through the book :) Looking forward to it!
