### ISSUE TITLE
Page 96: Text Updates

### ISSUE THREAD

**Issue by stavarotti** [abuiles/ember-cli-101-errata#117]
Original text:

> The filter function behaves similarly to find, but it takes an additional parameter known as the filter
> function. This will call the function for every record in the result and return the ones for which the
> function returns true.

Updated text:

> The filter method behaves similarly to find however, in addition to the type, it also takes a parameter known as the filter function. The filter method is called once for every record in the result and returns those for which the filter function returns true.

**Comment by abuiles** [comment]
Thanks!  Updated like

> The **filter** function behaves similarly to **find** however, in
> addition to the type, it also takes a parameter known as the **filter
> function**. The filter function is called once for every record in the
> result and returns those for which the filter function returns true.
