### ISSUE TITLE
Page 87 ember install:addon is invalid

### ISSUE THREAD

**Issue by StonJarks** [abuiles/ember-cli-101-errata#118]
First of all, I really thank you for this great book. I'm currently on page 87 and realized an error while running the command ember install:addon ember-browserify. 
It yields the error message "The specified command install:addon is invalid, for available options see ember help."

I'm currently running on version 0.14, node: 0.10.28, npm: 2.1.10
Any suggestions?

**Comment by abuiles** [comment]
@StonJarks hey! thanks, I just realized that I forgot to mention with the release notes that you should update to the latest version of ember-cli which adds the install command, please follow the steps here and let me know if it works https://github.com/ember-cli/ember-cli/releases/tag/v0.1.5 :)

**Comment by StonJarks** [comment]
Wow, what a lightning-fast response!
Everything working fine now. 
Thanks for this great book and the great support!

**Comment by abuiles** [comment]
@StonJarks thank you!

**Comment by Fryie** [comment]
With v0.2.3, the command doesn't appear to exist. However, `ember install ember-browserify` seems to work.
