### ISSUE TITLE
Page 112: Incorrect controller type specified

### ISSUE THREAD

**Issue by NotJustClarkKent** [abuiles/ember-cli-101-errata#119]
PDF Page 112 should be an **ArrayController** so: `export default Ember.ArrayController.extend` rather than `export default Ember.Controller.extend`.

Copying and pasting the code as-written results in the console error:
`Error: Assertion Failed: ArrayProxy expects an Array or Ember.ArrayProxy, but you passed object`

**Comment by abuiles** [comment]
@NotJustClarkKent thanks! I've rework this chapter to not use ArrayController, I'll be releasing soon with notes on the workaround.
