### ISSUE TITLE
Pages: 22, 23 Route generator can now create nested routes

### ISSUE THREAD

**Issue by tylergaw** [abuiles/ember-cli-101-errata#125]
> The Route generator doesn’t know how to create nested routes in router.js, so we have to fix that. Go to app/router.js and make sure the route we just generated is nested under the resource friends:

app/router.js

``` javascript
this.resource('friends', function(){ 
  this.route('new');
});
```

As of ember-cli 0.1.5 this is no longer needed, because you fixed it @abuiles :+1: :100: https://github.com/ember-cli/ember-cli/pull/2748

**Comment by abuiles** [comment]
Thanks! this is fixed in the latest release of the book.
