### ISSUE TITLE
Page 83-84: Actually there is no more "Error when importing ic-ajax"

### ISSUE THREAD

**Issue by vais** [abuiles/ember-cli-101-errata#127]
Something must have changed in ember-cli 1.5, but there is no longer any error importing ic-ajax - simply doing `app.import('bower_components/ic-ajax/dist/named-amd/main.js');` just works.

**Comment by tylergaw** [comment]
Same thing for me here. After uninstalling `ember-cli-ic-ajax` and installing `ic-ajax` with bower, importing `main.js` worked.

I tried a couple few different things; deleted `/dist` and `/tmp`, restarted server. Also cleared npm's cache with `npm cache clean`, and restarted the server. Importing `main.js` without whitelisting still worked and never gave an import error.

**Comment by rkrdo** [comment]
I can also confirm that it isn't happening for me either

**Comment by IanVS** [comment]
Same here.  I couldn't find any obviously related recent changes in the ember-cli github.  

@abuiles, do you know what's going on here? Thanks!

**Comment by jbinto** [comment]
+1, I did not need to whitelist exports. All of the instructions on page 85, 86 are not necessary.

ember 1.10.0, ember-cli 0.2.0-beta.1.

**Comment by jbinto** [comment]
And the same thing again on page 87.

``` javascript
app.import('bower_components/borrowers-dates/index.js', { exports: {
    'borrowers-dates': [
      'format'
] }
});
```

The above can be replaced with this:

``` javascript
app.import('bower_components/borrowers-dates/index.js');
```

**Comment by Fryie** [comment]
Same here. Also I find the explanations to be quite confusing, I'm not really sure what is supposed to be going on there.

**Comment by abuiles** [comment]
@Fryie thanks, the behavior was actually changed, now it just fails silently. I'l rework this part :)
