### ISSUE TITLE
Page 76: Might be better to not use the isDirty condition

### ISSUE THREAD

**Issue by tylergaw** [abuiles/ember-cli-101-errata#129]
In the code snippet for using the deactivate hook in "app/routes/friends/edit.js" there is a check to see if the model is dirty, if so, rollback.

``` javascript
import Ember from 'ember';

export default Ember.Route.extend({ 
  deactivate: function() {
    var model = this.modelFor('friends/edit');

    if (model.get('isDirty')) { 
      model.rollback();
    }
  }
});
```

According to [the docs](http://emberjs.com/api/data/classes/DS.Model.html#method_rollback) for `rollback` it does the `isDirty` check for you:

> If the model isDirty this function will discard any unsaved changes

I wonder if the snippet would be better without the condition?

``` javascript
import Ember from 'ember';

export default Ember.Route.extend({ 
  deactivate: function() {
    var model = this.modelFor('friends/edit');
    model.rollback();
  }
});
```

In my usage of it, it works exactly the same. However, I could see keeping the condition in place if other things needed to happen besides just rolling the model back.

**Comment by abuiles** [comment]
You are correct, we can avoid the use of isDirty here. 

It will be like you proposed on the next release.

Thanks!
