### ISSUE TITLE
Page 71: Is model.isDirty the correct item to observe?

### ISSUE THREAD

**Issue by paulochoi** [abuiles/ember-cli-101-errata#130]
I am wondering whether it would be better to observe on the model state for the selection in page 71's code?

The reason why I am bringing this up is that if you change the selection once model.dirty becomes TRUE, however, if you move the selection once again to the original option, model.dirty will still be FALSE.

**Comment by IanVS** [comment]
I noticed this also, the save is done every-other-time when switching back and forth between borrowed and returned.  I don't understand why that happens though, because if it saves, shouldn't the next change always make it dirty again?

**Comment by sirneb** [comment]
@IanVS The problem looks like the isDirty flag is not observed correctly because the isDirty flag looks to be working as you described.

**Comment by IanVS** [comment]
When I look in Ember Inspector, the `isDirty` will flash true for a moment along with `isSaving` the first time a change is made.  Setting it back to the original value does not change `isDirty` or `isSaving` but does change `state`.  However, the state change seems to happen only in the `Attributes`.  If I check `DS.Model`, the `state` inside `data` never changes (unless the page is refreshed).

Additionally, two XHR PUT requests are sent each time a save is made, for some reason.  Observing on model.state as suggested by @makwanza results in a single XHR PUT for each change, and a successful save.

@abuiles I'm really curious what's happening here.  I've tried to reason it out, but I don't have enough experience yet.  What's the difference between the `state` in the `DS.Model` and in the `Attributes`?  Why isn't `isDirty` behaving as we would expect?

**Comment by abuiles** [comment]
I've replaced this to observe the property `state` which is the one we are changing. it fixes the problem we were seeing with dirty.
