### ISSUE TITLE
Page 100: English language

### ISSUE THREAD

**Issue by vais** [abuiles/ember-cli-101-errata#131]
`We switch to v2 of the API, which side-loads all the articles records for our friend but doesn’t stop to understand what is happening.`
Perhaps:
`We switched to v2 of the API, which side-loads all the article records for our friends but didn’t stop to understand what was happening.  (or "but didn't stop to understand how that worked"?)`

**Comment by abuiles** [comment]
Thanks!  It will be fixed on the next release.

Replaced it with

> We switched to v2 of the API, which side-loads all the article records
> for our friend but didn't stop to understand how that worked.
