### ISSUE TITLE
The Computed Properties Gotchas solution is unclear

### ISSUE THREAD

**Issue by tylergaw** [abuiles/ember-cli-101-errata#135]
The problem that you describe in the section makes sense

> The downside of this is that they will be recalculated even if the value is the same.

After that though, it's unclear what I'm supposed to to. If I follow the text and the sample code a full solution isn't given. If I only install `ember-computed-change-gate` and update the friend model with the `capitalizedFirstName` property I do not get to see the problem described above–"they will be recalculated"–solved.

I think you could fix this by showing an example of using `capitalizedFirstName` somewhere. I'm not sure that's necessary though. Showing the code snippet for `changeGate` seems to break the flow of this section. I think mentioning that there are gotchas with computed properties and maybe linking to Change-gate would be enough. Using it seems outside the scope of the book.

To drive it home a bit more, the last sentence of the section:

> Now our computed property capitalizedFirstName will be called only when the value of the
> dependent key has changed to a different value.

That makes sense, but how does it benefit the borrowers app that we're building and where can I see the results?

**Comment by abuiles** [comment]
I removed this in favor of the actions down data up pattern.
