### ISSUE TITLE
Page 85: reinstalling the ember-cli-ic-ajax add-on

### ISSUE THREAD

**Issue by rkrdo** [abuiles/ember-cli-101-errata#137]
In page 85, you list the command to reinstall the ic-ajax add-on as `$ npm i ember-cli-ic-ajax --save`, but running that adds the add-on under `dependencies` instead of under `devDependencies` on the package.json, shouldn't the command be `npm i ember-cli-ic-ajax --save-dev` ?

**Comment by abuiles** [comment]
You are correct, this has been fixed, and available in the next release.
