### ISSUE TITLE
Page 50: Delete action should only transition once destroyRecor() promise is fulfilled.

### ISSUE THREAD

**Issue by WenInCode** [abuiles/ember-cli-101-errata#138]
On page 50 we call `destroyRecord()` then `transitionTo(...)` without waiting for the promise to be returned. 

original: `app/routes/friends.js`

```
delete: function(friend) {
  friend.destroyRecord();
  this.transitionTo('friends.index');
}
```

Doesn't this risk getting errors like the following for trying to transition before the promise has returned success/failure: 
`Error: Attempted to handle event`pushedData`on <... > while in state root.deleted.inFlight. ...`

Shouldn't we be doing the following:

```
delete: function(friend) {
  var _this = this;
  friend.destroyRecord().then(function() {
    _this.transitionTo('friends.index');
  });
}
```

**Comment by abuiles** [comment]
:+1:  thanks, it makes sense to do this, I've added it and will be available in the next release.
