### ISSUE TITLE
Page: 97 Link https://www.igvita.com/slides/2012/devtools-tips- and-tricks/ doesn't work

### ISSUE THREAD

**Issue by hinok** [abuiles/ember-cli-101-errata#141]
```
https://www.igvita.com/slides/2012/devtools-tips- and-tricks/
```

is unavailable

```
http://www.igvita.com/slides/2012/devtools-tips-and-tricks/
```

returns 404

**Comment by abuiles** [comment]
Thanks, I just tried it and it works fine, I think you need to click it instead of copy it. I just replace it with a reference to the presentation name instead of the URL making it clickable.

**Comment by hinok** [comment]
Yep now it works. Maybe site was offline for a moment.

**Comment by abuiles** [comment]
@hinok great, thanks!
