### ISSUE TITLE
Ember.ArrayController is mentioned without explaining

### ISSUE THREAD

**Issue by IanVS** [abuiles/ember-cli-101-errata#145]
Ember.ArrayController is mentioned in the chapter "Using Item controller to mark an article as returned." but is not defined or explained.  I couldn't find any in my code so far, so I'm not sure why it's brought up at this section of the book.  

Also, I read that they are not recommended (https://gist.github.com/samselikoff/1d7300ce59d216fdaf97), but I don't really understand the reason.

**Comment by abuiles** [comment]
@IanVS thanks! I'm in the process of rewriting that chapter without using an array controller. I didn't put much details into that since I'll be changing that soon. I'll let this open until I have fixed the issue. 

Thanks!

**Comment by abuiles** [comment]
thanks! I've rework this chapter to not use ArrayController, I'll be releasing soon with notes on the workaround.
