### ISSUE TITLE
Error importing moment with browserify

### ISSUE THREAD

**Issue by IanVS** [abuiles/ember-cli-101-errata#149]
I am able to install ember-browserify and npm install moment, and successfully build my app.  However, as soon as I add `import moment from 'nmp:moment';` I see this:

```
Cannot find module 'moment' from '/mnt/EmberCliRamdisk/borrowers/core_object-input_staging-NyEcH0pc.tmp'
Error: Cannot find module 'moment' from '/mnt/EmberCliRamdisk/borrowers/core_object-input_staging-NyEcH0pc.tmp'
    at /mnt/sdb1/code/websites/borrowers/node_modules/ember-browserify/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:50:17
    at process (/mnt/sdb1/code/websites/borrowers/node_modules/ember-browserify/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:119:43)
    at /mnt/sdb1/code/websites/borrowers/node_modules/ember-browserify/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:128:21
    at load (/mnt/sdb1/code/websites/borrowers/node_modules/ember-browserify/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:60:43)
    at /mnt/sdb1/code/websites/borrowers/node_modules/ember-browserify/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:66:22
    at /mnt/sdb1/code/websites/borrowers/node_modules/ember-browserify/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:21:47
    at Object.oncomplete (fs.js:108:15)
```

Any suggestions what I should take a look at?  I tried deleting `tmp` and allowing it to be rebuilt, restarting my laptop, uninstalling and reinstalling moment and ember-browserify several times, installing using `npm install --save-dev ember-browserify` as specified in https://github.com/ef4/ember-browserify, all with no luck.

**Comment by IanVS** [comment]
This appears to be a problem with using ember-cli-ramdisk.  If I remove that addon, everything is fine.

**Comment by abuiles** [comment]
@IanVS thanks! maybe can you report that to ember-browserify? @ef4 is that a known issue?

**Comment by IanVS** [comment]
I have reported to ember-browserify and ember-cli-ramdisk, since I'm not sure where the issue actually is.

**Comment by ef4** [comment]
Browserify is picky about where your tmp is. I bet that's the problem.

**Comment by abuiles** [comment]
@IanVS closing, seems seems related with ramdisk?
