### ISSUE TITLE
Add space: Page 28

### ISSUE THREAD

**Issue by elrickvm** [abuiles/ember-cli-101-errata#15]
In this snippet `“...data to python -mjson.tool...”` there should be a space after `-m` should read `“...data to python -m json.tool...”`

Here, in `“When returning a list Ember-Data expects the root of the payload to be the type of the model on plural (friends)...”` I believe that "on" needs to be "in". Also to clarify that you are talking about the name associated with the root json payload you could say as a possible suggestion, `“When returning a list Ember-Data expects the root name of the JSON payload to match the name of the model but pluralized (friends)”`

**Comment by abuiles** [comment]
Thanks you so much! I just fixed this and apply the suggestions.

**Comment by elrickvm** [comment]
No problem! Very much enjoying the book. Excellent job!
