### ISSUE TITLE
Page 103: Async API Example

### ISSUE THREAD

**Issue by IanVS** [abuiles/ember-cli-101-errata#155]
At the end of the second paragraph of _Working with async relationships in Ember-Data_, to get the articles with IDs of 40 and 41, wouldn't the GET request be something like /api/**articles**?ids=40,41 rather than /api/**friends**?ids=40,41

**Comment by abuiles** [comment]
Thanks, I fixed that and also change the params to be like /api/articles?ids%5B%5D=40&ids%5B%5D=41
