### ISSUE TITLE
Page 68 - 71

### ISSUE THREAD

**Issue by elrickvm** [abuiles/ember-cli-101-errata#16]
On page 68 you have an {{#each}} helper and within that you have this code `“{{#link-to 'friends.show' this}}”` showing that you can pass a reference to the current model by passing "this" in the link-to helper.

Then on page 69 you start explaining about a gotcha with the model hook firing on the friend.show route when passing a model vs model.id  in the link-to helper such as `...“{{#link-to ‘friends.show’ friend}} we’ll have to do {{#link-to ‘friends.show’ friend.id}}”`. However, as the code is written you will have to change the `{{#each}}` helper on page 68 to be `{{#each friend in model}}` to accommodate the above mention code and also this code on pg 69 `“{{link-to friend.fullName 'friends.show' friend}}”`. If you want to keep the each helper as you currently have it written all references to `friend` need to be `this`.

To someone that knows Ember they would probably pick that up but someone newer will go insane....lol..

This is just a suggestion but here on page 69.
   `“If our friend model had a property call fullName we could have written the helper like:
      {{link-to friend.fullName 'friends.show' friend}}” ...`

You are referencing fullName making it seem as though it is why you are able to rewrite the block style link-to helper into the new syntax inline-form of the helper. However I think you can remove that and just start  with pg 70...`“We already talked about computed properties, so let’s add one called fullName to app/models/friend.js”`.

Then on pg 71 you switch from the block form of the link-to helper to the new syntax inline form `“{{link-to friend.fullName 'friends.show' friend}}”`. Maybe you keep with the block-form there such as: 

  `{{#link-to 'friends.show' friend}}
     {{friend.fullName}}
   {{/link-to}}`

Then say for example "We could rewrite this block form of the link-to helper into a inline form using a new syntax" then show your inline form that you had. Again this will help for people not too familiar with Ember or people that have not seen that syntax.

**Comment by abuiles** [comment]
@elrickvm thanks, I have address most of your comments, they'll be available in the next release. I'm leaving the ticket open because there is another correction I want to make based on your last comment.

**Comment by elrickvm** [comment]
No problem. Thanks for taking the time to review.
