### ISSUE TITLE
Update borrowers example repository

### ISSUE THREAD

**Issue by IanVS** [abuiles/ember-cli-101-errata#161]
It seems that the "abuiles/borrowers" repository is not up-to-date, which is unfortunate because I think it could really help me out.  I'm completely stuck at adding the filtering to articles (page 120), I think because I don't completely understand itemController.  I'm glad that there are "tasks" in the book which do not have obvious solutions, but after a few hours of working at this, I'm ready to give up and look at how it should be done.

**Comment by abuiles** [comment]
Thanks for the heads up, I've working on a different branch, I'll merge it later today. In the meantime, I'll be in the irc channel in an hour or so if you need help.

**Comment by IanVS** [comment]
Just an idea, but it would be really nice to have separate branches for each chapter of the book.  So when reading along, we could see how the code should look at the end of each section. 

Someone on IRC helped me last night, but I still don't have a good understanding how it works. I think I just need to learn more about basic Ember.Js, which isn't really the scope of your book.  I've sure leaned a lot from your book, though. Thanks.
