### ISSUE TITLE
Deprecation warning in articles/index for {{#each}}

### ISSUE THREAD

**Issue by stefanbruvik** [abuiles/ember-cli-101-errata#165]
Using `itemController='articles/item'` in `templates/articles/index.hbs` gives deprecation warning:

```
DEPRECATION: Using the context switching form of {{each}} is deprecated. Please use the keyword form (`{{#each foo in bar}}`) instead.
```

**Comment by abuiles** [comment]
This should be fixed with today's update, now we are using components instead of itemsControllers.
