### ISSUE TITLE
Controller => ArrayController at page 205

### ISSUE THREAD

**Issue by stefanbruvik** [abuiles/ember-cli-101-errata#167]
When using `Ember.Controller.extend` as written in the code example at page 205, Ember throws an error: `Uncaught Error: Assertion Failed: ArrayProxy expects an Array or Ember.ArrayProxy, but you passed object`

Changing to `Ember.ArrayController.extend` fixes this.

(I'm using `Ember 1.10.0`)

**Comment by abuiles** [comment]
Are you reading on an ebook reading? Do you know which is the PDF page?

**Comment by abuiles** [comment]
This should be fixed now that we don't depend on Array Controllers.
