### ISSUE TITLE
Replace use of formatted-date from itemController => article-row component

### ISSUE THREAD

**Issue by samanthamichele7** [abuiles/ember-cli-101-errata#168]
On page 83, the book is still referring to the old itemController implementation within app/templates/articles/index.hbs for the formatted-date helper, even though that was replaced by the article-row component. The book should instead have the user update templates/components/articles/article-row.hbs.

**Comment by jbinto** [comment]
+1, just hit this myself.

**Comment by abuiles** [comment]
@samanthamichele7 thanks! I've fixed this, so we use it in the article-row... 

It will be available in today's release.
