### ISSUE TITLE
Page 11 - Footnote 27 links to 404

### ISSUE THREAD

**Issue by et** [abuiles/ember-cli-101-errata#169]
On Page 11, Footnote 27 `Enable ENV.APP.LOG_RESOLVER` links to a 404'ing link: https://github.com/abuiles/borrowers/commit/a66df6683eccedfcf185db23801bfc865e3dab3

**Comment by jbinto** [comment]
Correct URL is

https://github.com/abuiles/borrowers/commit/a66df6683eccedfcf185db23801bfc865e3ddba3

Looks like it got mangled somehow, the SHAs are way too close to be coincidental.

**Comment by abuiles** [comment]
Thanks! this will be available in today's release.
