### ISSUE TITLE
Page 14

### ISSUE THREAD

**Issue by jvenator** [abuiles/ember-cli-101-errata#17]
Following the mention of adapterFor the (i) block should read (italics are the changes)...

We can see that there is a look up for the friend and application adapter in ~~two~~ _four_ places **borrowers/friend/adapter, borrowers/adapters/friend, borrowers/applica- tion/adapter and borrowers/adapters/application**. ember-cli allows us to group things which are logically related under a single directory, such structure is known as PODS. We’ll work with the normal structure and at the end of the book rewrite a part of our code to be ~~structure~~ _structured_ under PODS.

**Comment by abuiles** [comment]
the typos are fixed.

> four places borrowers/friend/adapter, borrowers/adapters/friend, borrowers/applica- tion/adapter and borrowers/adapters/application

Is actually 2 places for each type, so 2 lookups for friend adapter and 2 for application.
