### ISSUE TITLE
date-helpers-test failing

### ISSUE THREAD

**Issue by stgallagher** [abuiles/ember-cli-101-errata#173]
I needed to make the following changes to the test code in `tests/unit/utils/date-helpers-test.js`:

``` javascript
import { module, test } from 'ember-qunit';
import Ember from 'ember';
import dateHelpers from '../../../utils/date-helpers';

module('Utils: formatDate');

test('formats a date object', function(assert) {
  var date = new Date("11-3-2015");
  var result = dateHelpers.formatDate(date, 'ddd MMM DD YYYY');

  assert.equal(result, 'Mon Nov 03 2014', 'returns a readable string');
});
```

I needed to:
- include `module` and `test` from `ember-qunit`
- import `dateHelpers` from `../../../utils/date-helpers`
- namespace the call to `formatDate` with `dateHelpers`
- add a second argument, 'ddd MMM DD YYYY', to `formatDate`

**Comment by abuiles** [comment]
thanks! 

I've fixed all the tests to match the new format, it will be available in today release.   

Also I released a tool recently to help you upgrade your tests :) http://blog.abuiles.com/blog/2015/02/25/upgrading-your-ember-cli-qunit-tests-in-less-than-5-minutes/
