### ISSUE TITLE
Page 70: Can use new {{else if}} syntax as of Ember 1.10

### ISSUE THREAD

**Issue by jbinto** [abuiles/ember-cli-101-errata#175]
The `article-row.hbs` code fragment at the top of Page 70 can be rewritten using the new `{{else if}}` chained helper, as per http://emberjs.com/blog/2015/02/07/ember-1-10-0-released.html#toc_chained-else-blocks

**Comment by abuiles** [comment]
Thanks! It'll be available in today's release :)
