### ISSUE TITLE
Page 129: Pods chapter incorrectly nested under testing

### ISSUE THREAD

**Issue by jbinto** [abuiles/ember-cli-101-errata#177]
Looks like the markdown for the "Pods" section got mangled somehow, as it appears to be nested under "Testing Ember.js applications".

**Comment by abuiles** [comment]
@jbinto thanks! seems like a issue with leanpub, I'll check with the upcoming release, this should be fixed.

**Comment by abuiles** [comment]
@jbinto indeed it was a leanpub issue, it will be fixed soon :)
