### ISSUE TITLE
Wrong closing of the br element on page 54 & 65.

### ISSUE THREAD

**Issue by brianvanburken** [abuiles/ember-cli-101-errata#178]
At the end of each `{{input}}` stands a `</br>` tag. The slash is supposed to go on the other side of the tag like this `<br/>` or with HTML5 there it is not required to close the br tag and can be written like this `<br>`.This is present in the version published on _2015-02-26_.
In the new HTMLBars engine you'll get the following error:

``` bash
File: borrowers/templates/friends/-form.hbs
Closing tag `br` (on line 4) did not match last open tag `fieldset` (on line 3).
```

**Comment by abuiles** [comment]
@brianvanburken thanks! I've fixed this and it will be available in today's release.
