### ISSUE TITLE
Page 16 - value of $E gets reset on browser refresh

### ISSUE THREAD

**Issue by jvenator** [abuiles/ember-cli-101-errata#18]
It should probably be noted on page 16, and perhaps on page 12 when first referenced, that instances of Route, Controller, View or Model assigned to $E via the Ember inspector are reset every time the browser gets refreshed. This requires you to jump back into Ember inspector and assign the appropriate resource to $E again.

**Comment by abuiles** [comment]
Thanks! Added a note on the info section of page 13.
