### ISSUE TITLE
Pg. 70-71: article index controller not created prior to first 'adding' to it

### ISSUE THREAD

**Issue by kbjorklid** [abuiles/ember-cli-101-errata#181]
Text: "Before using our components, let’s add to our articles index controller a property called possibleStates which we’ll use to pass down to the component:"

And then a snippet of code which does not contain the full file. Searching the book PDF with the file name and path ("app/controllers/articles/index.js") does not yield any results, so I believe the creation of that file has not been instructed, and it is not clear what else, outside that snippet, should be in the file.

**Comment by abuiles** [comment]
@kbjorklid thanks for reporting! I'm currently traveling but I plan to work on this issues before the end of the week. Remember the generators are your friends :), you can do ember g controller articles/index

**Comment by abuiles** [comment]
@kbjorklid thanks, added an info box to mention how to generate the controller, It'll be available in the next release.
