### ISSUE TITLE
Page 113: snippet file name path incorrect

### ISSUE THREAD

**Issue by kbjorklid** [abuiles/ember-cli-101-errata#182]
Snippet file name is `app/controller/articles/index.js`, should be `app/controllers/articles/index.js` (controllers should be plural).

To explain why I think this is a bit more higher priority (IMO) than it would first seem: this makes it harder to find the snippets related to a file since using the search function in the PDF does not match to all the snippets.

**Comment by abuiles** [comment]
@kbjorklid thanks! I've fixed this it will be available in today's release :)
