### ISSUE TITLE
Clearly indicate user action needed

### ISSUE THREAD

**Issue by friksa** [abuiles/ember-cli-101-errata#188]
When user action is required, use consistent convention of listing the filename with the content is not used.

p54 By default, we’ll use the Application Index Route as the dashboard. For now, we are going to create the file app/templates/index.hbs and write <h2>Dashboard</h2>.

**Comment by abuiles** [comment]
@friksa thanks! this will be fixed in the next release, I'll keep an eye on other sections when this happens.
