### ISSUE TITLE
Ember v2

### ISSUE THREAD

**Issue by friksa** [abuiles/ember-cli-101-errata#189]
It would be good to have a chapter on getting ready for Ember v2 so when you start a new project to do it in a way that is "probably" going to be easy to migrate to Ember v2.

When reading about Ember v2, the recommendation seems to be to use components instead of controllers.  I am not sure what that all implies, but it would be nice to address that in the example early on.

Note:  since I am new to Ember I might be misunderstanding the Ember v2 plans.

**Comment by abuiles** [comment]
@friksa thanks! I'm constantly updating the book so it paves the way towards 2.0, the use of components instead of controllers is not yet possible but as soon as it is I'll be updating the book to follow that :). I plan to update with the new changes in Ember as they appear.
