### ISSUE TITLE
{{link-to}} example on page 33 not working

### ISSUE THREAD

**Issue by jvenator** [abuiles/ember-cli-101-errata#19]
With the fullName attribute now available it is suggested to use the following link-to handlebars code, however this fails to render anything (just blank bullet points on the /friends page).

`{{link-to friend.fullName 'friends.show' friend}}`

Using the following seems to work...

`{{link-to fullName 'friends.show' this}}`

**Comment by abuiles** [comment]
@jvenator thanks! is updated and will be available in the next release
