### ISSUE TITLE
Page 49: Need to add Picnic's "plugins.min.css" to Brocfile.js

### ISSUE THREAD

**Issue by Oladele** [abuiles/ember-cli-101-errata#193]
Truly, great book so far! Hopefully, this is helpful...

On page 49 (book version downloaded from 3/30/15 email update), I think the following line needs to be added to the Brocfile.js instructions for Picnic css dependency:

```
app.import('bower_components/picnic/releases/plugins.min.css');
```

This is needed for the "-header.hbs" `<nav>` UI element (introduced on page 51) to get its Picnic styling which is not included in the plain picnic.css but is included in Picnic's plugins.css

**Comment by alexthornton** [comment]
+1

**Comment by jimbeaudoin** [comment]
:+1:

**Comment by abuiles** [comment]
Thanks everyone! this will be fixed in today's release :)
