### ISSUE TITLE
page 112 typo '

### ISSUE THREAD

**Issue by ChangJoo-Park** [abuiles/ember-cli-101-errata#199]
setObserver: function() {

this.addObserver(article.state', this, this.stateChanged); // article.state with ' ?

// we need to call get on the property so the observers are setup

// see for more info http://cl.ly/1f0Y1v2A1G04

this.get('article').get('state');

}.on('init'),

stateChanged: function() {

if (this.get(article.isDirty') && !this.get(article.isSaving')) {

Ember.run.once(this, this.autoSave);

}

}

**Comment by abuiles** [comment]
I simplified this in today's release, thanks!
