### ISSUE TITLE
Page 19 typo.

### ISSUE THREAD

**Issue by tgxworld** [abuiles/ember-cli-101-errata#200]
![screenshot from 2015-05-04 17 15 14](https://cloud.githubusercontent.com/assets/4335742/7451243/268fe55a-f281-11e4-9c7f-d25b60792b3c.png)

The current template generates [`Welcome to Ember.js`](https://github.com/ember-cli/ember-cli/blob/18d377b264859548f41aba6c3ea2015b90978068/blueprints/app/files/app/templates/application.hbs) instead of `Welcome to Ember`.

**Comment by abuiles** [comment]
@tgxworld thanks! it will be welcome to ember in the next release of ember-cli :)

**Comment by tgxworld** [comment]
@abuiles No worries! Thank you for the great book :+1:
