### ISSUE TITLE
page 49: picnic

### ISSUE THREAD

**Issue by BigGillyStyle** [abuiles/ember-cli-101-errata#205]
Regarding code snippet of "Adding picnic to the bundle":

`app.import('bower_components/picnic/releases/plugins.min.css'); app.import('bower_components/picnic/releases/picnic.min.css');`

The import of 'plugins.min.css' is not needed, and you have already corrected that in the example source code (but not in the book print).

**Comment by abuiles** [comment]
@BigGillyStyle thanks Andy!

Actually I think we need this to get picninc to work fine, I forgot push the source code update.

Thanks!
