### ISSUE TITLE
Page 82 - htmlbars instead of handlebars

### ISSUE THREAD

**Issue by rich-poole** [abuiles/ember-cli-101-errata#206]
Ember CLI defaults to htmlbars now, probably worth updating for this at some point :)

**Comment by hashemi** [comment]
Also note HTMLBars.makeBoundHelper is a little different than Handlebars, the correct code becomes:

``` javascript
export default Ember.HTMLBars.makeBoundHelper(function(params) {
  var date = params[0];
  var format = params[1];
  return formatDate(date, format);
});
```

**Comment by NickChristensen** [comment]
:+1: @AhmadH, this just tripped me up for a few minutes.
