### ISSUE TITLE
Pg 35 - Suggestion for link-to

### ISSUE THREAD

**Issue by albhardy** [abuiles/ember-cli-101-errata#209]
I had assertion error when inserting `friend.fullName` into link-to before I realized that there's difference between  {{#link-to friend.fullName 'friends.show' friend.id}}  {{/link-to}} and {{link-to  friend.fullName  'friends.show' friend}}. 

```
Uncaught Error: Assertion Failed: The attempt to link-to route 'Luis Mendoza' failed. The router did not find 'Luis Mendoza' in its possible routes: 'loading', 'error', 'friends.loading', 'friends.error', 'friends.new', 'friends.show', 'friends.index', 'friends', 'index', 'application'
```

Perhaps highlighting that once we have the computed property, we need to replace block expression link-to as inline-helper would be helpful.

**Comment by bennyz** [comment]
I agree, this confused me too

**Comment by abuiles** [comment]
I added a note about this in the release which will be out today. thanks!
