### ISSUE TITLE
Pg 43 Clarifying add Delete Link Action

### ISSUE THREAD

**Issue by albhardy** [abuiles/ember-cli-101-errata#210]
I was slightly confused when it is mentioned "to support deletion on Friends Show Route, we just need to add the same link with the action delete and implement the action". 

The link is not really same actually. In app/templates/friends/index.hbs, we use `<td><a href="#" {{action "delete" friend}}>Delete</a></td>` but in app/templates/friends/show.hbs, we should use `<li><a href="#" {{action "delete" model}}>Delete</a></li>` . Might be helpful to add the sample code there.

**Comment by abuiles** [comment]
Thanks! I'll rewrite this :)
