### ISSUE TITLE
API Endpoint dead

### ISSUE THREAD

**Issue by jtsom** [abuiles/ember-cli-101-errata#213]
The API endpoint at http://api.ember-cli-101.com seems to be dead. It just returns an error page:

The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

Has it changed / moved? There hasn't been a book update in a while, so if there were changes, I see nowhere it's been communicated.

**Comment by abuiles** [comment]
@jtsom hey! the api is working, it doesn't have a root end-point, try clicking here http://api.ember-cli-101.com/api/friends

re: update, I'm waiting for 2.0  to send a big update, that are some many moving things in the last couple of releases so I'll rather wait.
