### ISSUE TITLE
Page 40

### ISSUE THREAD

**Issue by elrickvm** [abuiles/ember-cli-101-errata#22]
**Typo:** 'nede' should be 'need'

Excerpt from book:
 `We can edit a friend now but we nede a way to reach the edit screen from the user profile page.`

PS. Sorry for the strange page numbers before I just noticed that if I resize my window in myBooks on my mac it will adjust the page numbers. So I pulled the number from the pdf version.

**Comment by abuiles** [comment]
Fixed, thanks!

**Comment by elrickvm** [comment]
Welcome sir!
