### ISSUE TITLE
Does Brocfile need to be changed in book in light of https://github.com/ember-cli/ember-cli/issues/4446?

### ISSUE THREAD

**Issue by timkellogg** [abuiles/ember-cli-101-errata#224]
According to issue on Ember-cli today, it looks like there might be a change with how the Brocfile.js is used in 1.13 as described in the book.  Link here: https://github.com/ember-cli/ember-cli/blob/master/TRANSITION.md.  It looks like it has transitioned from Brocfile to ember-cli-build.js.

**Comment by abuiles** [comment]
Thanks, I'm aware of this and I'm already fixing it through the book, I'll close it as soon as I release :)
