### ISSUE TITLE
standardize {{#each}} usages

### ISSUE THREAD

**Issue by bambery** [abuiles/ember-cli-101-errata#227]
Location 1685 shows the following in app/templates/articles/index.hbs:

{{#each model as |article|}}

This method of iterating hasn't been shown before. Previously, it was {{#each article in model}}, which is being deprecated ( http://emberjs.com/deprecations/v1.x/#sts=in syntax for {{each}} ). Could you please update the earlier references to switch to the new version?

**Comment by abuiles** [comment]
Thanks, I'm aware of this deprecation, I'm going through the whole book fixing this :)

Also the change from Brofile to ember-cli-build.
