### ISSUE TITLE
reword paragraph at location 1701

### ISSUE THREAD

**Issue by bambery** [abuiles/ember-cli-101-errata#228]
There is a paragraph which begins "We are iterating over every article in the model and then rendering...". The paragraph is two long and grammatically incorrect sentences. I'd suggest a better phrasing, but I am not clear on the precise meaning of the text. If you could please rewrite this entire paragraph, it would reduce confusion.

**Comment by abuiles** [comment]
@bambery what about the following:

> In the code above, we are iterating over the model, rendering an
> articles-row component for each item. We are passing as attributes
> the article, bounding the save action to another action which is also
> called "save" and finally binding the `articleStates` to the list of
> `possibleStates` in the controller. We could have call both
> properties the same but we did not, so we could demonstrate that we
> are only assigning
