### ISSUE TITLE
Page 47

### ISSUE THREAD

**Issue by elrickvm** [abuiles/ember-cli-101-errata#23]
Picnic: does not have latest.min.css in its bower repo so app.import will through an error saying
‘You must pass a file to app.import....’ consider updating code to address that update to their repo.

**Current** Code:
`app.import('bower_components/picnic/releases/latest.min.css');`

**Update** Code suggestion:
`app.import('bower_components/picnic/releases/v2.3.min.css');`

**Comment by abuiles** [comment]
@elrickvm can you please download the latest version? it is fixed in there. 

Thanks!

**Comment by elrickvm** [comment]
Ok cool.. Just downloaded it. Thanks!
