### ISSUE TITLE
PG 52-58

### ISSUE THREAD

**Issue by elrickvm** [abuiles/ember-cli-101-errata#24]
A note to add an `{{outlet}}` to the articles template needs to be added cause without it the articles.index will not render because of the presence of the articles template.

On page 52 a resource is created for articles through the CLI which in turn creates a template for articles.

Then on page 56 a template for articles/index is created and code is added to it. Articles.index route to show a list of borrowed books which is nested within the friends.show route. The added {{outlet}} will allow a place for articles.index to render cause that will render into articles template then that will render into friends.show outlet.

**Comment by elrickvm** [comment]
Aaahhhh ok...I just checked the link at the bottom of the page which showed all the changes in the repo for that chapter and the added `{{outlet}}`is in the articles templates. I dont think its mentioned in the chapter though.

**Comment by abuiles** [comment]
@elrickvm Thanks! the blueprint has been fixed so running `ember generate resource articles description:string createdAt:date state:string notes:string` generates the right blueprint.
