### ISSUE TITLE
Page 63

### ISSUE THREAD

**Issue by esbanarango** [abuiles/ember-cli-101-errata#28]
Missing 'var' on example.
![ember-cli-101_pdf__page_67_of_152_](https://cloud.githubusercontent.com/assets/1156865/5059675/8826a732-6cf2-11e4-8e37-0e49560c222e.png)
![borrowers](https://cloud.githubusercontent.com/assets/1156865/5059684/afdb49f4-6cf2-11e4-9211-8ab1abb62acc.png)

**Comment by abuiles** [comment]
@esbanarango that's fine, you can create more than one variable in a single line, maybe you close the first line with `;` instead of `,`? 

It should be like

```
      var _this = this,
      model = this.modelFor('articles/new');
```

**Comment by esbanarango** [comment]
@abuiles Right! My fault, I had it with `;` instead of `,`. Thanks!

**Comment by rbeene** [comment]
You weren't the only one who hit this one.

**Comment by esbanarango** [comment]
@rbeene :+1:

**Comment by abuiles** [comment]
@rbeene thanks! I'll change that to be one var per var :)
