### ISSUE TITLE
Page 14-15: Missing output and file names

### ISSUE THREAD

**Issue by kgish** [abuiles/ember-cli-101-errata#35]
Bottom of page 14:

Run ember g adapter application to create an application adapter like the following:

```
$ ember g adapter application
version: 0.1.2
installing
  create app/adapters/application.js
installing
  create tests/unit/adapters/application-test.js
```

Top of page 15:

Application Adapter => app/adapters/application.js

Extending from ActiveModelAdapter => app/adapters/application.js

**Comment by abuiles** [comment]
Fixed, thanks!
