### ISSUE TITLE
Partials start with _ not with -

### ISSUE THREAD

**Issue by Serabe** [abuiles/ember-cli-101-errata#4]
When creating a new friend it is mentioned at least twice the partial `-form` where it should be `_form`, if you want it to be truly a partial, or `form` if you want it to be a normal template (see that the `partial` helper will look for `form` if `_form` is not found).

First time it is mentioned is in:

> **app/templates/friends/-form.hbs** with the following content: [code]

And then in a _key_ block shortly after the partial code:

> [...] followed by the partial name: **-form.hbs**.

**Comment by abuiles** [comment]
@Serabe probably I miss to mention this, but on ember-cli partials need to start with `-`

**Comment by Serabe** [comment]
My fault, didn't read carefully the _key_ block. I'll try to finish the book in the following two days or so.
