### ISSUE TITLE
Page 43: TransitionTo is deprecated

### ISSUE THREAD

**Issue by kgish** [abuiles/ember-cli-101-errata#40]
On page 43, the following line:

```
this.transitionTo('friends.index');
```

should be:

```
this.transitionToRoute('friends.index');
```

**Comment by WenInCode** [comment]
@kgish @abuiles did you mean page 43? If so is transitionToRoute not a method of a Ember.controller, not Ember.route? I may have missed the notes on deprecation, but as of the current docs, it seems as though this is fine.

**Comment by kgish** [comment]
I meant page 43, sorry. Updated comment.

I get a warning that it's deprecated.

```
Ember Inspector 1.6.3
Ember 1.7.0
Ember Data 1.0.0-beta.10
Handlebars 1.3.0
jQuery 1.11.1
```

**Comment by abuiles** [comment]
@kgish hey thanks! Because we are in a Route `transitionTo` is fine, if we were in a controller then `transitionToRoute` should be used.
