### ISSUE TITLE
Suggestion: include file names in code listings

### ISSUE THREAD

**Issue by kgish** [abuiles/ember-cli-101-errata#43]
To make it easier it would be good if you consistently include the name of the file commented at the top of the code examples, for example:

```
//app/models/article.js
...
```

I notice that sometimes you do this, but often not which is a bit confusing and makes it more difficult for the reader who has to search through the text above for the file name.

Hope this helps.

**Comment by abuiles** [comment]
thanks! I just correct this :), it would be like this on tomorrow's release.
