### ISSUE TITLE
Page 56: route or resource?

### ISSUE THREAD

**Issue by kgish** [abuiles/ember-cli-101-errata#48]
On page 56, when you nest the `articles` resource under `show` :

```
this.route('show', { path: ':friend_id' }, function() {
    this.resource('articles', function() { });
});
```

Shouldn't the `route` be changed to a `resource` now that it is no longer a leaf and now a parent?

```
this.resource('show', { path: ':friend_id' }, function() {
   ...
});
```

**Comment by abuiles** [comment]
@kgish the use of route here is fine, we just want to use that to namespace all the following routes (whch are articles).

The main idea is to show that you can now have nested  `route` and `resources` under `route`, also it seems like `resource` will be going away in favor of only having `route`.

Thanks!

**Comment by kgish** [comment]
Okay, now it makes sense, just sometimes confusing for me. Didn't know that resources will be removed, will make everyone's life easier.
