### ISSUE TITLE
Page 52: heading case

### ISSUE THREAD

**Issue by xymbol** [abuiles/ember-cli-101-errata#51]
Where it reads:

> New Friend And Friend profile template

It should probably read:

> New friend and friend profile templates

I've noticed different case styles in headings across chapters.

**Comment by abuiles** [comment]
@xymbol yes, this is actually intentional but I might need to fix some scenarios, I want to related it somehow with the route they are related with, and they'll display in camel case in the inspector most of the times.

**Comment by xymbol** [comment]
I'd make it consistent through the text. Using class names would be great but, probably worse for a faster reading experience. Then, given that classes are exported as anonymous ES6 modules then naming is not that relevant.

**Comment by abuiles** [comment]
@xymbol that makes sense, I'll start to fix it as I find them, it might  take some time since there are a lot of those ones :)
