### ISSUE TITLE
Page 68: ember g controller articles/item --type=basic

### ISSUE THREAD

**Issue by kgish** [abuiles/ember-cli-101-errata#55]
When I run the command `ember g controller articles/item` I get the following warning:

```
Warning: no controller type was specified, defaulting to basic. Specify using --type=basic|object|array
```

I believe that you want to include the `--type=basic` to avoid confusion on the part of the reader.

**Comment by abuiles** [comment]
@kgish I removed mentions to `--type` since it will be deprecated on the next release of ember-cli. it will come out I think before the end of this week.

**Comment by kgish** [comment]
Default? Seems a bit dangerous when one needs to specify an ArrayController instead. No matter I guess since Ember 2.0 is moving away from controllers anyway.
