### ISSUE TITLE
Text runs off the page (22)

### ISSUE THREAD

**Issue by WenInCode** [abuiles/ember-cli-101-errata#6]
Hi Adolfo, 

On page 22 the text for the url seems to run right off the page, I know what it's supposed to say but I figured I'd give you a heads up.
![screenshot 2014-10-19 23 52 56](https://cloud.githubusercontent.com/assets/5448834/4696943/c8ccce2c-581d-11e4-88c2-654930547721.png)

**Comment by abuiles** [comment]
OK, I had to rework this part, but is fixed, thanks!
