### ISSUE TITLE
Page 74: article route changed?

### ISSUE THREAD

**Issue by kgish** [abuiles/ember-cli-101-errata#64]
On page 74, there is an ongoing discussion about reloading the data from the server or not. You point to the following example code:

```
// app/routes/articles/index.js
import Ember from 'ember';

export default Ember.Route.extend({
    model: function() {
        return this.store.find('friend');
    }
});
```

It is not clear what this means. Is this supposed to replace the previous file contents above? Or just replacing `return this.modelFor('friends/show').get('articles')` with `return this.store.find('friend')` ? Or is it just a hypothetical example showing what we 'might' have done to reload data?

**Comment by abuiles** [comment]
thanks for pointing this out! 

The title for that snippet is incorrect, actually I think we don't need it there, I just removed it.
