### ISSUE TITLE
Page 80: export default function

### ISSUE THREAD

**Issue by kgish** [abuiles/ember-cli-101-errata#65]
Wouldn't the following declaration be more consistent?

```
// app/utils/date-helpers.js
export default function formatDate(date, format) {
  return window.moment(date).format(format);
}
```

instead of:

```
function formatDate(date, format) {
...
export {
  formatDate
};
```

**Comment by abuiles** [comment]
@kgish thanks! Since we want this module to export date helpers, we don't want to make any of the possible helpers the defaults.

What I mean is that we could eventually have something like 

```
function formatDate(date, format) {
}
function parseDate(date) {
}

export {
  formatDate,
  parseDate
}
```

And keep the module open to extensions.  I added a note on my TODOs so I mention this on the book.

**Comment by kgish** [comment]
Alright, now I get it. I wasn't aware that this was possible. Of course, this should only be used to group similar functions, otherwise they should be put in other modules.
