### ISSUE TITLE
Typo in Hands-On/The input helper (page 29)

### ISSUE THREAD

**Issue by WenInCode** [abuiles/ember-cli-101-errata#7]
Top of page 29, "the description in **Frien details**" --> "the description in **Friend details**"

**Comment by WenInCode** [comment]
There is another small typo near the bottom of page 40
"if we notice both **Friends Edit Route** and **Friends Edit Route** share the..." --> "if we notice both **Friends Show Route** and **Friends Edit Route** share the..."

**Comment by abuiles** [comment]
@twendlandt fixed! thanks
