### ISSUE TITLE
Page 118: Model is not refreshed

### ISSUE THREAD

**Issue by kgish** [abuiles/ember-cli-101-errata#79]
After making the changes to `app/controllers/friends/index.js` on page 117 and the changes to `app/routes/friends/index.js` on page 118, no additional API request is being made.

Rather than seeing `/api/v4/friends?sortBy=fullName&sortAscending=true` I just the the usual `/api/v4/friends` for some weird reason.

```
DEBUG: -------------------------------
DEBUG: Ember      : 1.7.0
DEBUG: Ember Data : 1.0.0-beta.10
DEBUG: Handlebars : 1.3.0
DEBUG: jQuery     : 1.11.1
DEBUG: -------------------------------
```

**Comment by abuiles** [comment]
Did you change the model hook? I just tested in my app and this work.
