### ISSUE TITLE
Page 116:  cursor pointer

### ISSUE THREAD

**Issue by kgish** [abuiles/ember-cli-101-errata#80]
When one clicks on the table column headers Name and Article, the contents are indeed toggled between ascending and descending.

However, would be better if css changed so that cursor pointer appears on mouse over, or embed with an <a>-tag could also work.

**Comment by tylergaw** [comment]
This may prove to be short-sighted, but for this I added:

``` css
[data-ember-action] {
  cursor: pointer;
}
```

I'm going to use that in a project I'm working on. Makes sense (at the moment) that all html elements that have an action associated with them would on clickable in mouse-enabled devices where this shows up.

**Comment by abuiles** [comment]
@tylergaw thanks! I've added the cursor to the TR :), will be available on the next release.
