### ISSUE TITLE
Pages 78-92

### ISSUE THREAD

**Issue by xymbol** [abuiles/ember-cli-101-errata#84]
## Page 78 (as numbered)

Where it reads:

> Even so, if there is an AMD definition included in the library, not all of them are compatible with the modules loader used by ember-cli.

It should probably read:

> Even so, if there is an AMD definition included in the library, not all of them are compatible with the module loader used by ember-cli.

Where it reads:

> Unfortunately, the modules loader ember-cli is using doesn’t support that yet.

It should probably read:

> Unfortunately, the ember-cli module loader doesn’t support that yet.
## Page 80

Where it reads:

> Here we are wrapping the call to moment#format in the function formatDate, which we can consume doing import { formatDate } from ‘utils/date-helpers’;,.

It should probably read:

> Here we are wrapping the call to moment#format in the function formatDate, which we can consume doing import { formatDate } from 'utils/date-helpers';.
## Page 82

Where it reads:

> Next we need to add the library to bower.

It should probably read:

> Next we need to add the library to Bower.
## Page 84

Where it reads:

> Now that we understand how importing named-amd libraries works, we can remove the import for ic-ajax from the Brocfile.js and use it via the addon.

It should probably read:

> Now that we understand how importing named AMD libraries works, we can remove the import for ic-ajax from the Brocfile.js and use it via the addon.
## Page 85

Where it reads:

> Let’s consume a simple named-amd library that takes a date and returns its value after calling .toDateString(). 

It should probably read:

> Let’s consume a simple named AMD library that takes a date and returns its value after calling .toDateString().
## Page 86

Where it reads:

> In this chapter we have covered how to work with JavaScript plugins both as globals and as consuming named-amd plugins.

It should probably read:

> In this chapter we have covered how to work with JavaScript plugins both as globals and as consuming named AMD plugins.
## Page 92

In the code example:

```
export default Ember.Component.extend({
  length: 100, // Default length and width would 100 width: 100,
```

I would rather use height instead of length.

**Comment by abuiles** [comment]
@xymbol señor mil gracias! going out in the next release.
