### ISSUE TITLE
Various errata for the 11/28 release

### ISSUE THREAD

**Issue by straydogstudio** [abuiles/ember-cli-101-errata#86]
Using the PDF for page numbers.

Page 36: In app/templates/friends/edit.hbs I had to use `{{model.fullName}}` in the header to get a result.

Page 42: `#friend in model` should be `#each friend in model`

Page 73: "set a and b continuously" should probably be "set a and b consecutively" since each is called once (right after it says the observer is called twice.)

Page 96: The friends will disappear if the "total number of articles is _odd_" not even. 

I believe these are mentioned in the pull request by xymbol:
Page 128: "Until know" should be "Until now". "grouping things by their time" should be "grouping things by their type".

Page 139: "which makes super easy" should be "which makes it super easy"

Page 140: It took me a while to realize that Ember and Ember data would be updated by this process, since they weren't explicitly upgraded in the example. The title refers to upgrading ember-cli, and the second paragraph mentions 0.0.46 and 0.1.X but doesn't say Ember (later I realized those were Ember release numbers), and the bower.json file doesn't see a change in Ember or Ember data versions. I suggest two things:
- change "using version 0.0.46" to say "using Ember version 0.0.46" so a newbie doesn't miss what you are referring to.
- Have the bower.json diff reflect the changes from 0.0.46 to 0.1.X

Given, of course, that I could have done something wrong, you can see my repo here: https://github.com/straydogstudio/borrowers

**Comment by abuiles** [comment]
Thanks! I apply all the changes you suggested, they'll be available in the next release.

About updating ember-cli, we are actually updating ember-cli version not ember/ember-data.

I added a note so it's clear that their version might change too:

```
I> In this scenario Ember and Ember-Data didn't change but it might
I> happen from time to time that Ember and Ember-Data get updated to
I> their latest available release, in case we don't want to update those
I> libraries we can just ignore the changes to those lines.
```
