### ISSUE TITLE
page 41, "Cancel action doesn't work properly" ? 

### ISSUE THREAD

**Issue by AndreiMotinga** [abuiles/ember-cli-101-errata#89]
file    app/controllers/friends/edit.js

import FriendsBaseController from './base';
export default FriendsBaseController.extend({
  actions: {
    cancel: function() {
      this.transitionToRoute('friends.show', this); 
       // shouldn't it be    this.transitionToRoute('friends.show', this.get('model'));   ? 
      return false;
    }
  }
});

When hit cancel,  show template is being generated without model

**Comment by kgish** [comment]
This is fixed later on, keep going a bit further in the book.

**Comment by DavidVII** [comment]
Hey @AndreiMotinga, I just ran into this issue too. You're right! This should be `this.transitionToRoute('friends.show', this.get('model'));`

Just spoke to @abuiles on twitter and it looks like there will be a fix for this in the pipeline!

**Comment by abuiles** [comment]
Thanks, I just fixed this.
