### ISSUE TITLE
Line brake

### ISSUE THREAD

**Issue by rderoldan1** [abuiles/ember-cli-101-errata#9]
Hi Adolfo. 

130 readers :+1: congrats !!
In page 2 at the last line, you missed a line brake, so the file name is out of the margin
![screen shot 2014-10-21 at 10 47 04 am](https://cloud.githubusercontent.com/assets/968973/4721565/8e6ba844-5939-11e4-9eab-75c3d29fba3b.png)

**Comment by abuiles** [comment]
Fixed, thanks!
