### ISSUE TITLE
Moment.js  server restart? 

### ISSUE THREAD

**Issue by AndreiMotinga** [abuiles/ember-cli-101-errata#92]
I had some issues when working with moment.js - I couldn't get things to work until restart the server I believe. 
I might be wrong so the question is ,  should I restart the server each time I make a change to Brocfile? if so  I believe it should be mentioned.

**Comment by abuiles** [comment]
@AndreiMotinga yes, we should, I added a note about this :)

**Comment by AndreiMotinga** [comment]
I believe for a beginner as myself - it'll be useful to note. Thanks )
