### ISSUE TITLE
Suggestion: Chapter on OAuth2 Resource Owner Password Credentials

### ISSUE THREAD

**Issue by mech** [abuiles/ember-cli-101-errata#94]
Many of use are using basic Rails has_secure or Devise tradition password with session for authentication and viewing protected pages/APIs. It will be nice if you are able to include such a chapter on OAuth2 Resource Owner Password Credentials for those of us looking into such solution and integration.

**Comment by abuiles** [comment]
Hey, thanks! This is outside the scope of the book.  

I was thinking about creating a series of posts to describe how to do this but then I just saw http://appallingfarrago.com/ember/embercli/github/divshot/torii/rails/2014/12/07/ember-cli-torri-rails.html series about doing auth with ember, so what I've been thinking is to create a further reading/resources chapter with links to all this useful articles.

**Comment by mech** [comment]
OOoo.. great understand it is out of scope. Tks for the link :)
