### ISSUE TITLE
Page 140+

### ISSUE THREAD

**Issue by kgish** [abuiles/ember-cli-101-errata#95]
I would say that the whole section starting on page 140 with `Updating your project to the latest version of ember-cli` is a waste of paper and as far as I am concerned can be removed with a reference to the ember-cli website where this is explained as well.

Better to use the extra space left over for more valuable stuff ;)

**Comment by abuiles** [comment]
@kgish thanks! the upgrade process on the ember-cli website is only limited to the commands but doesn't really walks you through.

I've done this process live with other people and they have found it valuable and learn new tools and tricks from it, so I'll keep it, thanks.

**Comment by kgish** [comment]
Okay then, that makes sense. Only that you will have to keep your information in sync with the ember-cli website which will involve extra work for you.
