### ISSUE TITLE
Observing Collections: extend from Ember.ArrayController

### ISSUE THREAD

**Issue by alanbhamilton** [abuiles/ember-cli-101-errata#96]
Currently in the Observing Collections section we're extending from Ember.Controller

_app/controller/articles/index.js_

``` javascript
import Ember from 'ember';

export default Ember.Controller.extend({
```

I'm getting the following error in the browser console:

```
Uncaught Error: Assertion Failed: ArrayProxy expects an Array or Ember.ArrayProxy, but you passed object
```

Should be extending from ArrayController:

``` javascript
export default Ember.ArrayController.extend({
```

**Comment by abuiles** [comment]
@alanbhamilton thanks! maybe could you push your repo so I have a look? It's working on my end.

**Comment by alanbhamilton** [comment]
@abuiles the code in question is on page 111 (PDF). The book is suggesting to extend from `Ember.Controller`. You can check out the state of my repo when I was having this problem at [this branch](https://github.com/alanbhamilton/borrowers/tree/abuiles). Thanks.

**Comment by mariozig** [comment]
In the version of the PDF i have, the error is on page 112.
@alanbhamilton thanks for posting this here -- extending from `ArrayController` fixes things.

**Comment by abuiles** [comment]
Can you please try again?  I have it as follows and it works fine, also which version of ember are you on?

```
import Ember from 'ember';

export default Ember.Controller.extend({
  queryParams: ['sortBy', 'sortAscending'],
  contentDidChange: function() {
    console.log('Called when we add or removed an article.');
  }.observes('model.[]'),
  stateDidChange: function() {
    console.log('Called when the state property change for any of the articles.');
  }.observes('model.@each.state')
});
```

**Comment by stgallagher** [comment]
This issue is still occurring for me. I'm using Ember 0.1.15. The OP's fix seems to work, though.
