### ISSUE TITLE
Page 118: sortBy=Names missing in the url

### ISSUE THREAD

**Issue by kgish** [abuiles/ember-cli-101-errata#98]
When I click on the `Names` column I see the following url:

```
http://0.0.0.0:4200/friends
http://0.0.0.0:4200/friends?sortAscending=true
http://0.0.0.0:4200/friends
...
```

Whereas when I click on the `Articles` column I see this:

```
http://0.0.0.0:4200/friends?sortAscending=true&sortBy=totalArticles
http://0.0.0.0:4200/friends?sortBy=totalArticles
http://0.0.0.0:4200/friends?sortAscending=true&sortBy=totalArticles
...
```

I would expect `&sortBy=Names` to appear above but for some reason it's missing.

Is this a bug or have I done something wrong?

Also I see that a request is being fired off with each click:

```
XHR finished loading: GET "http://0.0.0.0:4200/api/v4/friends".
```

Is this correct?

**Comment by abuiles** [comment]
Thanks! I need to mention that, when we are in the default query param, it doesn't show in the url, that's why you don't see Names, because that's the default value for the sortBy query parameter.

**Comment by kgish** [comment]
Right, that's what I thought. Then you need to fix the incorrect link on the same page, namely:

```
/api/v4/friends?sortBy=fullName&sortAscending=true
```

should be changed to:

```
/api/v4/friends?sortAscending=true&sortBy=totalArticles
```

**Comment by abuiles** [comment]
@kgish `/api/v4/friends?sortBy=fullName&sortAscending=true` is correct, that would be how it looks by default.

**Comment by kgish** [comment]
That's weird, I never see that, only the urls shown above.
